name: CI

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Kernel Build Action
        uses: dabao1955/kernel_build_action@v1.3
        with:
          kernel-url: https://github.com/Fauxly/android_kernel_xiaomi_sm8475
          branch: lts
          config: unicorn_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
