name: CI

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Kernel Build Action
        uses: dabao1955/kernel_build_action@v1.3
        with:
          kernel-url: https://github.com/ahhhl/android_kernel_xiaomi_cepheus
          branch: main
          config: cepheus_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 13
          aosp-clang-version: r383902
          ksu: true
          lxc: true
          anykernel3: true
