name: action_kernel


on:
  workflow_dispatch:


jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download clang & kernel source
        run: |
          git clone https://github.com/kdrag0n/proton-clang clang --depth=1
          git clone https://github.com/Fauxly/android_kernel_xiaomi_sm8475 -b lts kernel --depth=1
          
      - name: Build kernel
        run: |
          export KBUILD_BUILD_USER="Fauxly"
          export KBUILD_BUILD_HOST="Unicorn-Kernel"
          args="                  O=out \
                                  ARCH=arm64 \
                                  SUBARCH=arm64 \
                                  CC=$GITHUB_WORKSPACE/clang/bin/clang \
                                  CLANG_TRIPLE=aarch64-linux-gnu- \
                                  CROSS_COMPILE=$GITHUB_WORKSPACE/clang/bin/aarch64-linux-gnu- \
                                  CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/clang/bin/arm-linux-gnueabi- "
          cd kernel          
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          sed -i 's/HyperOS/HyperOS-KSU/g' arch/arm64/configs/vendor/unicorn_defconfig
          sed -i 's/# CONFIG_MODULES is not set/CONFIG_MODULES=y/g' arch/arm64/configs/vendor/unicorn_defconfig
          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/vendor/unicorn_defconfig
          echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/vendor/unicorn_defconfig
          echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/vendor/unicorn_defconfig          
          make ${args} vendor/unicorn_defconfig && make -j$(nproc --all) ${args}
          
      - name: Package kernel
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/Xirudly/AnyKernel3 --depth=1
          rm -rf AnyKernel3/.git
          cp kernel/out/arch/arm64/boot/Image.gz AnyKernel3/
          zip -r Kernel_12spro AnyKernel3/
          
      - name: Upload kernel
        uses: actions/upload-artifact@v3
        with:
          name: Kernel_12spro
          path: AnyKernel3/*
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./Kernel_12spro.zip
